baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.6"
      filename = "Cryptomator-1.5.6-x64.exe"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/Cryptomator-1.5.6-x64.exe"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/Cryptomator-1.5.6-x64.exe.asc"
      checksum = "1eaaa64f81c11fa3c9ffa0a0de68f53a1d21231733bbe243ef500daea3e88d69"
    [params.releases.dmg]
      version = "1.5.6"
      filename = "Cryptomator-1.5.6.dmg"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/Cryptomator-1.5.6.dmg"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/Cryptomator-1.5.6.dmg.asc"
      checksum = "4bf5d453e957c647fcf14062046e6042159f4dda5b5b324ef0814bc950f30bd9"
    [params.releases.appimage]
      version = "1.5.6"
      filename = "cryptomator-1.5.6-x86_64.AppImage"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/cryptomator-1.5.6-x86_64.AppImage"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.6/cryptomator-1.5.6-x86_64.AppImage.asc"
      checksum = "4fe19465da92d0a2bc00a300e321632add700b0a2feecb8ee4abea3b74102e6c"
    [params.releases.android]
      version = "1.5.8"
      filename = "Cryptomator-1.5.8.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.8/Cryptomator-1.5.8.apk"
      checksum = "e291eb68cd044eddf15c6f3acc4472b7c2192e539024e092d152d85052a5b1ea"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
